Document: echoseven
Title: Debian echoseven Manual
Author: <insert document author here>
Abstract: This manual describes what echoseven is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/echoseven/echoseven.sgml.gz

Format: postscript
Files: /usr/share/doc/echoseven/echoseven.ps.gz

Format: text
Files: /usr/share/doc/echoseven/echoseven.text.gz

Format: HTML
Index: /usr/share/doc/echoseven/html/index.html
Files: /usr/share/doc/echoseven/html/*.html
